### ISSUE TITLE
Module 'Torch' not found, however I have pytorch installed

### ISSUE THREAD

**Issue by cgrain** [Eruvae/yolact_ros#11]
I have checked out branch ROS2, and build both yolact_ros and yolact_ros2_msgs.

However, when I try to start ```ros2 launch yolact_ros2 yolact_ros2.launch.py``` it gives an error ```ModuleNotFoundError: No module named 'torch' ```, which is weird because I have pytorch available if I run ``` conda list```
Also, when I run python in its shell, I can use ```import torch``` without any problems. I have reinstalled pytorch and torchvision, without much success. I have tried to rebuild everything using colcon, and that also warned me that it could not find torch, which I also have pasted below. 
I am using Foxy (Is that a problem? I would not think so, actually) and I am running out of options I should try. and below I have pasted some output of some checks I did: 

Colcon Build:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/distutils/core.py", line 215, in run_setup
    exec(f.read(), g)
  File "<string>", line 6, in <module>
ModuleNotFoundError: No module named 'torch'
[0.580s] ERROR:colcon.colcon_core.package_identification:Exception in package identification extension 'python_setup_py' in 'src/yolact/external/DCNv2': Command '['/usr/bin/python3', '-c', "import sys;from setuptools.extern.packaging.specifiers import SpecifierSet;from distutils.core import run_setup;dist = run_setup(    'setup.py', script_args=('--dry-run',), stop_after='config');skip_keys = ('cmdclass', 'distclass', 'ext_modules', 'metadata');data = {    key: value for key, value in dist.__dict__.items()     if (        not key.startswith('_') and         not callable(value) and         key not in skip_keys and         key not in dist.display_option_names    )};data['metadata'] = {    k: v for k, v in dist.metadata.__dict__.items()     if k not in ('license_files', 'provides_extras')};sys.stdout.buffer.write(repr(data).encode('utf-8'))"]' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/package_identification/__init__.py", line 143, in _identify
    retval = extension.identify(_reused_descriptor_instance)
  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 48, in identify
    config = get_setup_information(setup_py)
  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 261, in get_setup_information
    _setup_information_cache[hashable_env] = _get_setup_information(
  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 301, in _get_setup_information
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-c', "import sys;from setuptools.extern.packaging.specifiers import SpecifierSet;from distutils.core import run_setup;dist = run_setup(    'setup.py', script_args=('--dry-run',), stop_after='config');skip_keys = ('cmdclass', 'distclass', 'ext_modules', 'metadata');data = {    key: value for key, value in dist.__dict__.items()     if (        not key.startswith('_') and         not callable(value) and         key not in skip_keys and         key not in dist.display_option_names    )};data['metadata'] = {    k: v for k, v in dist.metadata.__dict__.items()     if k not in ('license_files', 'provides_extras')};sys.stdout.buffer.write(repr(data).encode('utf-8'))"]' returned non-zero exit status 1.

Starting >>> yolact_ros2_msgs
--- stderr: yolact_ros2_msgs                              
CMake Warning at /opt/ros/foxy/share/rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake:235 (add_library):
  Cannot generate a safe runtime search path for target
  yolact_ros2_msgs__rosidl_typesupport_fastrtps_c__pyext because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libssl.so.1.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/riwo-game-pc/anaconda3/envs/yolact38/lib
    runtime library [libcrypto.so.1.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/riwo-game-pc/anaconda3/envs/yolact38/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  /opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:48 (include)
  /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:286 (ament_execute_extensions)
  CMakeLists.txt:24 (rosidl_generate_interfaces)


---
Finished <<< yolact_ros2_msgs [5.94s]
Starting >>> yolact_ros2
Finished <<< yolact_ros2 [0.49s]          

Summary: 2 packages finished [6.96s]
  1 package had stderr output: yolact_ros2_msgs
```

Conda list:
```# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
astroid                   2.4.2                    py38_0  
blas                      1.0                         mkl  
ca-certificates           2020.7.22                     0  
catkin-pkg                0.4.22                   pypi_0    pypi
certifi                   2020.6.20                py38_0  
cudatoolkit               10.2.89              hfd86e86_1  
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.15                  pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
empy                      3.3.4                    pypi_0    pypi
freetype                  2.10.2               h5ab3b9f_0  
future                    0.18.2                   pypi_0    pypi
intel-openmp              2020.2                      254  
isort                     5.5.2                    py38_0  
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.2.0                    pypi_0    pypi
lark-parser               0.9.0                    pypi_0    pypi
lazy-object-proxy         1.4.3            py38h7b6447c_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
lz4-c                     1.9.2                he6710b0_1  
matplotlib                3.1.3                    pypi_0    pypi
mccabe                    0.6.1                    py38_1  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.2.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.1           py38hfd86e86_0  
numpy                     1.18.1                   pypi_0    pypi
numpy-base                1.19.1           py38hfa32c7d_0  
olefile                   0.46                       py_0  
opencv-python             4.2.0.32                 pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0  
pillow                    7.2.0            py38hb39fc2d_0  
pip                       20.2.2                   py38_0  
pycocotools               2.0.0                    pypi_0    pypi
pylint                    2.6.0                    py38_0  
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.8.5                h7579374_1  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
readline                  8.0                  h7b6447c_0  
setuptools                49.6.0                   py38_0  
six                       1.15.0                     py_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
toml                      0.10.1                     py_0  
torch                     1.6.0                    pypi_0    pypi
torchvision               0.5.0                    pypi_0    pypi
wheel                     0.35.1                     py_0  
wrapt                     1.11.2           py38h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
```
ros2 launch etc:
```
[INFO] [launch]: All log files can be found below /home/riwo-game-pc/.ros/log/2020-09-21-16-13-14-476990-riwo-game-pc-76104
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [yolact_ros2_node-1]: process started with pid [76106]
[yolact_ros2_node-1] Traceback (most recent call last):
[yolact_ros2_node-1]   File "/home/riwo-game-pc/yolact_ws/install/yolact_ros2/lib/yolact_ros2/yolact_ros2_node", line 11, in <module>
[yolact_ros2_node-1]     load_entry_point('yolact-ros2==0.1.0', 'console_scripts', 'yolact_ros2_node')()
[yolact_ros2_node-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
[yolact_ros2_node-1]     return get_distribution(dist).load_entry_point(group, name)
[yolact_ros2_node-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
[yolact_ros2_node-1]     return ep.load()
[yolact_ros2_node-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
[yolact_ros2_node-1]     return self.resolve()
[yolact_ros2_node-1]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
[yolact_ros2_node-1]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[yolact_ros2_node-1]   File "/home/riwo-game-pc/yolact_ws/install/yolact_ros2/lib/python3.8/site-packages/yolact_ros2/yolact_ros2.py", line 23, in <module>
[yolact_ros2_node-1]     import torch
[yolact_ros2_node-1] ModuleNotFoundError: No module named 'torch'
[ERROR] [yolact_ros2_node-1]: process has died [pid 76106, exit code 1, cmd '/home/riwo-game-pc/yolact_ws/install/yolact_ros2/lib/yolact_ros2/yolact_ros2_node --ros-args -r __node:=yolact_ros2_node --params-file /home/riwo-game-pc/yolact_ws/install/yolact_ros2/share/yolact_ros2/config/yolact_config.yaml'].
```

**Comment by arjunskumar** [comment]
@cgrain You should include python path of conda to the ROS2

**Comment by cgrain** [comment]
Well, another morning and another look showed that conda and ROS2 do not like each other. I disabled conda, and installed everything the old-school way. I got everything working now!
